apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        visualize: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
