apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    visualize: "true"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
# By default
  #type: ClusterIP
# NodePort :
  type: NodePort
# Cloud & Docker-for-Desktop:
  #type: LoadBalancer
# Otherwise:
  #type: NodePort